---
title: "Freshwater Creel Estimates"
date: "`r Sys.Date()`"
params:
  project_name: "District 14"
  fishery_name: "Skagit summer sockeye 2022"
  est_date_start: "2022-06-19"
  est_date_end: "2022-07-29"
  est_catch_groups: !r data.frame(rbind(
    c(species = 'Sockeye', life_stage = 'Adult|Jack|UNK|NA', fin_mark = 'UM|AD|UNK|NA', fate = 'Kept')
    ))
  person_count_type: "group"
  period_pe: "week"
  period_bss: "day"
  days_wkend: !r c('Saturday', 'Sunday')
  index_count_types: "Vehicle/Trailers Only"
  census_expansion: "Direct"
  min_fishing_time: 0.5
  output_location_filepath: "local"
  output_teams_name: "DFW-Team FP FW Creel Monitoring Program - General"
output:
  html_document:
    fig_caption: yes
    theme: default
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r setup, include=FALSE}
#running the 'setup' chunk loads the read-only `params` list
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 10, fig.height = 8)
library("here") #defines root at working dir of .Rproj
```

```{r first_time_run, eval=FALSE, include=FALSE}
# set up file paths
## top level for scripts and outputs
if (!dir.exists(here("fishery_analyses"))) {
  dir.create(here("fishery_analyses")); "fishery_analyses folder created"
}
## project level
if (!dir.exists(here("fishery_analyses", params$project_name))) {
  dir.create(here("fishery_analyses", params$project_name))
  paste(here("fishery_analyses", params$project_name), "folder created")
}
## fishery-specific
if (!dir.exists(here("fishery_analyses", params$project_name, params$fishery_name))) {
  dir.create(here("fishery_analyses", params$project_name, params$fishery_name))
  paste(here("fishery_analyses", params$project_name, params$fishery_name), "folder created")
}

#save the master template with new params arguments for the fishery
rstudioapi::documentSave(rstudioapi::getActiveDocumentContext()$id)
#make an appropriately renamed copy
file.copy(
  here("template_scripts/fw_creel.Rmd"),
  here("fishery_analyses", params$project_name, params$fishery_name, 
       paste0("fw_creel_", params$fishery_name, ".Rmd"))
)
#open the new copy
rstudioapi::documentOpen(
  here("fishery_analyses", params$project_name, params$fishery_name, 
       paste0("fw_creel_", params$fishery_name, ".Rmd"))
)

```

```{r packages_and_functions}
library("suncalc")
library("tidyverse")
library("patchwork")
library("gt")
theme_set(theme_light())

library("rstan")
rstan_options(auto_write = TRUE)

purrr::walk(list.files(here("R_functions"), full.names = T), source)
```

# `r paste(params$fishery_name)`

```{r}
gt(tibble(param = names(params), value = as.character(params)))
```

# Fetch raw data

```{r dwg_fetch, echo=FALSE}
dwg <- fetch_dwg(params$fishery_name)

# #to fix up Excel bunged date format
# read_csv("input_files/closures.csv", show_col_types = FALSE) |> 
#   mutate(event_date = as.Date(event_date, format = '%m/%d/%Y')) |> 
#   write_csv("input_files/closures.csv")

dwg$days <- prep_days(
  date_begin = params$est_date_start, 
  date_end = params$est_date_end, 
  weekends = params$days_wkend,
  holidays = read_lines(paste(here(), "input_files/dates_holidays_2015_2030.txt", sep = "/")),
  lat = mean(dwg$ll$centroid_lat), #can/should consider smarter options
  long = mean(dwg$ll$centroid_lon),#can/should consider smarter options 
  period_pe = params$period_pe,
  sections = unique(dwg$effort$section_num),
  closures = readr::read_csv(paste(here(),"input_files/closures.csv", sep = "/"), show_col_types = FALSE) |> 
    dplyr::filter(fishery_name == params$fishery_name)
  )
```

# Review fetched data

## Fishery sections

```{r table_sections}
dwg$effort |> 
  filter(location_type == "Section") |> 
  distinct(water_body, section_num, location) |> 
  arrange(section_num) |>
  select(`Water Body` = water_body, `Section Number` = section_num, `Location description` = location) |> 
  gt()
```

## Days

```{r gt_creel_days}
dwg$days |> 
  mutate(across(starts_with("open_"), ~if_else(., "open","closed"))) |> 
  rename_with(.cols = starts_with("open_"), .fn = ~str_remove_all(., "open_")) |> 
  gt::gt() |> 
  gt::data_color(
    columns = contains("section_"),
    colors = scales::col_factor(
      palette = c("#C3C7C3", "#78B574"),
      domain = c("closed","open")) 
  )
```

## Effort

```{r gt_creel_effort}
dwg$effort |>
  filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))) |> 
  distinct(section_num, location, event_date, tie_in_indicator, count_sequence) |> 
  count(section_num, location, tie_in_indicator) |> 
  mutate(tie_in_indicator = case_when(
    tie_in_indicator == 1 ~ "census",
    tie_in_indicator == 0 ~ "index"
  )) |>
  arrange(section_num, tie_in_indicator, location) |> 
  gt(groupname_col = "section_num", rowname_col = "location") |> 
  tab_style(
    style = list(cell_fill("grey70"), cell_text(weight = "bold")),
    locations = cells_body(rows = tie_in_indicator == "census")
  )
```

## Interview

```{r gt_creel_interview}
# dwg$interview |>  
#   filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))) |> 
#   count(section_num, fishing_location) |> 
#   arrange(section_num) |> 
#   gt(groupname_col = "section_num", caption = "Number of interviews by analysis section")

dwg$interview |>  
  filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))) |> 
  count(section_num, event_date) |> 
  pivot_wider(names_from = section_num, values_from = n) |> 
  arrange(event_date) |> 
  gt(rowname_col = "event_date") |> 
  sub_missing() |> 
  data_color(
    columns = where(is.numeric),
    colors = scales::col_quantile(
      palette = c("white", "orange"), 
      reverse = T, na.color = "grey",
      domain = NULL #c(0, )
    )
  )
```

## Catch

```{r gt_creel_catch}
dwg$catch |>
  left_join(dwg$interview, by = "interview_id") |> 
  filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))) |> 
  group_by(catch_group) |> 
  summarise(fish_count = sum(fish_count), .groups = "drop") |> 
  gt(caption = "Total reported encounters in interviews to date for catch groups defined as individual combinations of species, life state, fin mark, and fate")
```

# Shared data aggregation

```{r prep_dwg_summ_shared_summary_objects, echo=FALSE}
dwg_summ <- list() #intermediate objects wrangled from creel list elements

#get count_type levels from interview to ensure alignment...?

#prep_interview() no longer excludes observations with NA vehicle_count/trailer_count
#requires handling during summarization for fisheries/records where these were not collected
dwg_summ$interview <- prep_dwg_interview(
  dwg_interview = dwg$interview |> filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))),
  dwg_catch = dwg$catch,
  person_count_type = params$person_count_type,
  min_fishing_time = params$min_fishing_time,
  est_catch_groups = params$est_catch_groups 
  )

#Aggregates census (tie in) effort counts, associating to closest-in-time index count
dwg_summ$effort_census <- prep_dwg_effort_census(
  eff = dwg$effort |> filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))))

#Aggregates index effort counts over locations within count_seq & section
dwg_summ$effort_index <- prep_dwg_effort_index(
  eff = dwg$effort |> filter(between(event_date, as.Date(params$est_date_start), as.Date(params$est_date_end))))
```

# PE estimation

```{r prep_inputs_pe}
inputs_pe <- list()

#derive a table of potentially section-anglerType-specific values to modify census expansions
inputs_pe$census_expan <- prep_inputs_pe_census_expan(eff = dwg$effort, census_expansion = params$census_expansion)

# Calculate total days the fishery was open per strata (strata = period, day_type, and section_num)
inputs_pe$days_total <- prep_inputs_pe_days_total(days = dwg$days)

# depending on the types of index counts, reach the calc: ang_hrs_daily_mean_TI_expan = angler_hours_daily_mean * TI_expan_final
# when index counts are already bank & boat, matching census counts,
#   then angler_hour daily means are just effort index counts of anglers expanded by day length,
#   which are multiplied against tie-in expanded census counts of anglers by type (per section_num)
# but when index counts are trailers & vehicles,
#   then angler_hour daily means require first using interviews to estimate anglers_per_vhcl_trlr by angler_final total & boat 
#   so anglers_per_vhcl_trlr can be multiplied against the trailer & vehicle counts in effort_index, releveled to boat/total
#   and then TI-expanded counts similarly require splitting, re-leveling and rebinding census to boat/total to allow join with effort_index
#   and THEN generating a final object with total, boat and derived-bank, including dealing with case of only-bank (e.g., Cascade)
if(str_detect(params$index_count_types, "Bank|Boat")) {
  
  inputs_pe$ang_hrs_daily_mean <- prep_inputs_pe_ang_hrs_bank_boat(
    days = dwg$days, 
    dwg_summarized = dwg_summ,
    census_expan = inputs_pe$census_expan
    )
  
} else if(str_detect(params$index_count_types, "Vehicle|Trailer")) {
  
  #could skip retaining as list element and just pass as inline call in arg to next function
  inputs_pe$interview_ang_per_vhcl_trlr <- prep_inputs_pe_int_ang_per_vhcl_trlr(dwg_summarized = dwg_summ)
  
  inputs_pe$ang_hrs_daily_mean <- prep_inputs_pe_ang_hrs_vhcl_trlr(
    days = dwg$days, 
    dwg_summarized = dwg_summ,
    interview_ang_per_vehic = inputs_pe$interview_ang_per_vhcl_trlr,
    census_expan = inputs_pe$census_expan
    )
  
}

#aggregate interviews per day per strata of [week/month-weekend/day-section_num-bank/boat-est_cg]
#then multiply by TI-expanded effort estimate
#dropping any date-section_num-angler_final-catch_groups for which only interview-based CPUE is available
#but census-corrected effort estimates are not (various reasons why a day-section_num-angler_final hours could be NA)
inputs_pe$daily_cpue_catch_est <- prep_inputs_pe_daily_cpue_catch_est(
  days = dwg$days,
  dwg_summarized = dwg_summ,
  angler_hours_daily_mean = inputs_pe$ang_hrs_daily_mean
)

#THIS SEEMS WRONG/MISSING STRATA:  dplyr::group_by(section_num, angler_final)
inputs_pe$df <- prep_inputs_pe_df(
  days = dwg$days,
  angler_hours_daily_mean = inputs_pe$ang_hrs_daily_mean
)

```


```{r census_index_plot}

# test <- plot_paired_census_index(
#   days = dwg$days,
#   dwg_summarized = dwg_summ,
#   interview_ang_per_vehic = inputs_pe$interview_ang_per_vhcl_trlr,
#   census_expan = inputs_pe$census_expan
# )

things <- plot_paired_census_index(
  days = dwg$days,
  dwg_summarized = dwg_summ,
  interview_ang_per_vehic = inputs_pe$interview_ang_per_vhcl_trlr,
  census_expan = inputs_pe$census_expan
)

things[[1]]
things[[2]]
```


```{r estimates_pe}
estimates_pe <- list() 

estimates_pe$effort <- est_pe_effort(
  days = dwg$days,
  pe_inputs_list = inputs_pe
)

estimates_pe$catch <- est_pe_catch(
  days = dwg$days,
  pe_inputs_list = inputs_pe
)
 

# Next steps - 3.) update "inputs_pe$census_expan" object -- currenlty not using the indirect census expansion values from database due to naming issue in database (i.e., direct_census_bank should be indirect_census_boat) and ability/use of pivot_wider function to handle column header prefixes.

```

## summary PE

```{r PE_summary}

# effort by section_num

 estimates_pe$effort |>
        group_by(section_num) |> 
        summarise(
          E_sum = sum(est, na.rm=T),
          .groups = "drop"
        ) |> 
  pivot_wider(names_from = section_num, values_from = E_sum) |>
  gt(caption = paste("Estimated effort (angler hours) by fishing section from", params$est_date_start, "to", params$est_date_end))

estimates_pe$catch |> 
        group_by(est_cg, section_num) |>
        summarise(
          C_sum = sum(est),
          .groups = "drop"
        ) |> 
      pivot_longer(
        cols = -c(est_cg, section_num),
        names_to = "estimate",
        values_to = "PE"
      ) |> 
  select(est_cg, section_num, estimate, PE, everything()) |> 
  gt(groupname_col = "est_cg", caption = "Catch estimates for specified catch groups") |>
  fmt_number(-c(estimate, est_cg, section_num), decimals = 1) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "PE")
  ) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "PE")
  )

```

# BSS estimation

```{r prep_inputs_bss, eval=FALSE}
#either a single element list for a single catch_group
#or a list of bss-input-lists, one for each catch_group
inputs_bss <- unique(dwg_summ$interview$est_cg) |> 
  set_names() |> 
  map(
    ~prep_inputs_bss(
      est_catch_group = .x,
      period = params$period_bss,
      days = dwg$days,
      dwg_summarized = dwg_summ,
      #likely warrants revision? targeting n-gears-rows by n-sections-cols matrix of values
      tie_in_mat = dwg$effort |> 
        filter(tie_in_indicator == 1) |> 
        distinct(section_num, p_census_bank, p_census_boat) |> 
        pivot_longer(starts_with("p_census"), names_to = "ang", values_to = "val") |> 
        arrange(section_num) |> 
        pivot_wider(names_from = section_num, values_from = val) |> 
        select(-ang) |> 
        as.matrix(),
      priors = c(
        value_cauchyDF_sigma_eps_C = 0.5,
        value_cauchyDF_sigma_eps_E = 0.5,
        value_cauchyDF_sigma_r_E = 0.5,  
        value_cauchyDF_sigma_r_C = 0.5,  
        value_cauchyDF_sigma_mu_C = 0.5, 
        value_cauchyDF_sigma_mu_E = 0.5, 
        value_normal_sigma_omega_C_0 = 1,
        value_normal_sigma_omega_E_0 = 3,
        value_lognormal_sigma_b = 1,
        value_normal_sigma_B1 = 5,  
        value_normal_mu_mu_C = log(0.02),
        value_normal_sigma_mu_C = 1.5,  
        value_normal_mu_mu_E = log(5),
        value_normal_sigma_mu_E = 2,  
        value_betashape_phi_E_scaled = 1, 
        value_betashape_phi_C_scaled = 1 
      )
    )
  )

```

```{r estimates_bss, eval=FALSE}
#should work for either single or multiple catch_group 
estimates_bss <- list()

for(ecg in names(inputs_bss)) {
  gc(verbose = T)
  
  ecg_fit <- fit_bss(
    bss_inputs_list = inputs_bss[[ecg]],
    n_iter = 100
  )
  
  ecg_keep <- list()
  
  ecg_keep$overview <- get_bss_overview(bss_fit = ecg_fit, ecg = ecg)
  
  ecg_keep$catch_daily <- get_bss_catch_daily(bss_fit = ecg_fit, ecg = ecg)
  
  ecg_keep$effort_daily <- get_bss_effort_daily(bss_fit = ecg_fit, ecg = ecg)
  
  # #can write wrapper on tidybayes::spread_draws or write our own
  # #to repackage full posterior of key estimated quantities
  # #such as daily catch or something else?
  # ecg_keep$catch_daily_draws <- ecg_fit |> tidybayes::spread_draws(C[s][d,g]) #long, each index still a col 
  # ecg_keep$catch_daily_draws <- ecg_fit |> tidybayes::spread_draws(C[s][d,g] | g) #a bit wider, bank/boat pivoted wide 
  
  estimates_bss[[ecg]] <- ecg_keep
  #a little cleanup never hurts?
  rm(ecg_fit, ecg_keep); gc()
}


```

## summary BSS

```{r BSS_summary, eval= FALSE}

# effort by section_num

map_df(estimates_bss, ~.x$overview) |> 
  gt(groupname_col = "est_cg") |>
  fmt_number(-c(estimate, est_cg), decimals = 1) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "50%")
  ) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "50%")
  )

```

# PE/BSS combined summary

```{r combo_overview, eval=FALSE}
#per-est_cg summary of total effort hours and catch/encounters, showing results of both PE and BSS estimation methods

map_df(estimates_bss, ~.x$overview) |> 
  left_join(
    bind_cols(
      estimates_pe$catch |> 
        group_by(est_cg) |>
        summarise(
          C_sum = sum(est),
          .groups = "drop"
        ),
      estimates_pe$effort |> 
        summarise(
          E_sum = sum(est, na.rm=T),
          .groups = "drop"
        )
    ) |> 
      pivot_longer(
        cols = -est_cg,
        names_to = "estimate",
        values_to = "PE"
      )
    ,
    by = c("estimate", "est_cg")
  ) |> 
  select(est_cg, estimate, PE, everything()) |> 
  gt(groupname_col = "est_cg") |>
  fmt_number(-c(estimate, est_cg), decimals = 1) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "PE")
  ) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "PE")
  ) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "50%")
  ) |> 
  tab_style(
    style = cell_fill(), locations = cells_body(columns = "50%")
  )

```

# Save results

```{r write_out_results, eval = FALSE}
# bss_overview <- estimates_bss$summary_by_catchgroup
#write out a workbook with results from model runs 


## how to write out html to outputs file path??

# data fetched from dwg and summarized data used for PE and BSS (dwg_summ)
if(nchar(params$output_location_filepath) > 1) {
  writexl::write_xlsx(
  c(set_names(dwg, paste0("dwg_", names(dwg))), set_names(dwg_summ, paste0("dwg_summ", names(dwg_summ)))),
  path = file.path(wd_output, params$project_name, params$fishery_name, paste0("fetch_dwg_", params$fishery_name, params$est_date_start, params$est_date_end, ".xlsx"))
  )
}

# PE output
if(nchar(params$output_location_filepath) > 1) {
  writexl::write_xlsx(
  c(estimates_pe[rev(names(estimates_pe))]),
  path = file.path(wd_output, params$project_name, params$fishery_name, paste0("pe_output_", params$fishery_name, params$est_date_start, params$est_date_end, ".xlsx"))
  )
}

# overview of BSS output
# if(nchar(params$output_location_filepath) > 1) {
#   writexl::write_xlsx(bss_overview,
#   path = file.path(wd_output, params$project_name, params$fishery_name, paste0("bss_overview_", params$fishery_name, params$est_date_start, params$est_date_end, ".xlsx"))
#   )
# }
```
